/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.4.0
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.doubango.KycVerif.Sdk;

public class KycVerifSdkParallelDeliveryCallback {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected KycVerifSdkParallelDeliveryCallback(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(KycVerifSdkParallelDeliveryCallback obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(KycVerifSdkParallelDeliveryCallback obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        KYCDocumentsVerifSDKJNI.delete_KycVerifSdkParallelDeliveryCallback(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void onNewResult(KycVerifSdkResult newResult) {
    KYCDocumentsVerifSDKJNI.KycVerifSdkParallelDeliveryCallback_onNewResult(swigCPtr, this, KycVerifSdkResult.getCPtr(newResult), newResult);
  }

}
