//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.4.0
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace org.doubango.KycVerif.Sdk {

class KYCDocumentsVerifSDKPINVOKE {

  protected class SWIGExceptionHelper {

    public delegate void ExceptionDelegate(string message);
    public delegate void ExceptionArgumentDelegate(string message, string paramName);

    static ExceptionDelegate applicationDelegate = new ExceptionDelegate(SetPendingApplicationException);
    static ExceptionDelegate arithmeticDelegate = new ExceptionDelegate(SetPendingArithmeticException);
    static ExceptionDelegate divideByZeroDelegate = new ExceptionDelegate(SetPendingDivideByZeroException);
    static ExceptionDelegate indexOutOfRangeDelegate = new ExceptionDelegate(SetPendingIndexOutOfRangeException);
    static ExceptionDelegate invalidCastDelegate = new ExceptionDelegate(SetPendingInvalidCastException);
    static ExceptionDelegate invalidOperationDelegate = new ExceptionDelegate(SetPendingInvalidOperationException);
    static ExceptionDelegate ioDelegate = new ExceptionDelegate(SetPendingIOException);
    static ExceptionDelegate nullReferenceDelegate = new ExceptionDelegate(SetPendingNullReferenceException);
    static ExceptionDelegate outOfMemoryDelegate = new ExceptionDelegate(SetPendingOutOfMemoryException);
    static ExceptionDelegate overflowDelegate = new ExceptionDelegate(SetPendingOverflowException);
    static ExceptionDelegate systemDelegate = new ExceptionDelegate(SetPendingSystemException);

    static ExceptionArgumentDelegate argumentDelegate = new ExceptionArgumentDelegate(SetPendingArgumentException);
    static ExceptionArgumentDelegate argumentNullDelegate = new ExceptionArgumentDelegate(SetPendingArgumentNullException);
    static ExceptionArgumentDelegate argumentOutOfRangeDelegate = new ExceptionArgumentDelegate(SetPendingArgumentOutOfRangeException);

    [global::System.Runtime.InteropServices.DllImport("KYCDocumentsVerifSDK", EntryPoint="SWIGRegisterExceptionCallbacks_KYCDocumentsVerifSDK")]
    public static extern void SWIGRegisterExceptionCallbacks_KYCDocumentsVerifSDK(
                                ExceptionDelegate applicationDelegate,
                                ExceptionDelegate arithmeticDelegate,
                                ExceptionDelegate divideByZeroDelegate, 
                                ExceptionDelegate indexOutOfRangeDelegate, 
                                ExceptionDelegate invalidCastDelegate,
                                ExceptionDelegate invalidOperationDelegate,
                                ExceptionDelegate ioDelegate,
                                ExceptionDelegate nullReferenceDelegate,
                                ExceptionDelegate outOfMemoryDelegate, 
                                ExceptionDelegate overflowDelegate, 
                                ExceptionDelegate systemExceptionDelegate);

    [global::System.Runtime.InteropServices.DllImport("KYCDocumentsVerifSDK", EntryPoint="SWIGRegisterExceptionArgumentCallbacks_KYCDocumentsVerifSDK")]
    public static extern void SWIGRegisterExceptionCallbacksArgument_KYCDocumentsVerifSDK(
                                ExceptionArgumentDelegate argumentDelegate,
                                ExceptionArgumentDelegate argumentNullDelegate,
                                ExceptionArgumentDelegate argumentOutOfRangeDelegate);

    static void SetPendingApplicationException(string message) {
      SWIGPendingException.Set(new global::System.ApplicationException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingArithmeticException(string message) {
      SWIGPendingException.Set(new global::System.ArithmeticException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingDivideByZeroException(string message) {
      SWIGPendingException.Set(new global::System.DivideByZeroException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingIndexOutOfRangeException(string message) {
      SWIGPendingException.Set(new global::System.IndexOutOfRangeException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingInvalidCastException(string message) {
      SWIGPendingException.Set(new global::System.InvalidCastException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingInvalidOperationException(string message) {
      SWIGPendingException.Set(new global::System.InvalidOperationException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingIOException(string message) {
      SWIGPendingException.Set(new global::System.IO.IOException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingNullReferenceException(string message) {
      SWIGPendingException.Set(new global::System.NullReferenceException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingOutOfMemoryException(string message) {
      SWIGPendingException.Set(new global::System.OutOfMemoryException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingOverflowException(string message) {
      SWIGPendingException.Set(new global::System.OverflowException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingSystemException(string message) {
      SWIGPendingException.Set(new global::System.SystemException(message, SWIGPendingException.Retrieve()));
    }

    static void SetPendingArgumentException(string message, string paramName) {
      SWIGPendingException.Set(new global::System.ArgumentException(message, paramName, SWIGPendingException.Retrieve()));
    }
    static void SetPendingArgumentNullException(string message, string paramName) {
      global::System.Exception e = SWIGPendingException.Retrieve();
      if (e != null) message = message + " Inner Exception: " + e.Message;
      SWIGPendingException.Set(new global::System.ArgumentNullException(paramName, message));
    }
    static void SetPendingArgumentOutOfRangeException(string message, string paramName) {
      global::System.Exception e = SWIGPendingException.Retrieve();
      if (e != null) message = message + " Inner Exception: " + e.Message;
      SWIGPendingException.Set(new global::System.ArgumentOutOfRangeException(paramName, message));
    }

    static SWIGExceptionHelper() {
      SWIGRegisterExceptionCallbacks_KYCDocumentsVerifSDK(
                                applicationDelegate,
                                arithmeticDelegate,
                                divideByZeroDelegate,
                                indexOutOfRangeDelegate,
                                invalidCastDelegate,
                                invalidOperationDelegate,
                                ioDelegate,
                                nullReferenceDelegate,
                                outOfMemoryDelegate,
                                overflowDelegate,
                                systemDelegate);

      SWIGRegisterExceptionCallbacksArgument_KYCDocumentsVerifSDK(
                                argumentDelegate,
                                argumentNullDelegate,
                                argumentOutOfRangeDelegate);
    }
  }

  protected static SWIGExceptionHelper swigExceptionHelper = new SWIGExceptionHelper();

  public class SWIGPendingException {
    [global::System.ThreadStatic]
    private static global::System.Exception pendingException = null;
    private static int numExceptionsPending = 0;
    private static global::System.Object exceptionsLock = null;

    public static bool Pending {
      get {
        bool pending = false;
        if (numExceptionsPending > 0)
          if (pendingException != null)
            pending = true;
        return pending;
      } 
    }

    public static void Set(global::System.Exception e) {
      if (pendingException != null)
        throw new global::System.ApplicationException("FATAL: An earlier pending exception from unmanaged code was missed and thus not thrown (" + pendingException.ToString() + ")", e);
      pendingException = e;
      lock(exceptionsLock) {
        numExceptionsPending++;
      }
    }

    public static global::System.Exception Retrieve() {
      global::System.Exception e = null;
      if (numExceptionsPending > 0) {
        if (pendingException != null) {
          e = pendingException;
          pendingException = null;
          lock(exceptionsLock) {
            numExceptionsPending--;
          }
        }
      }
      return e;
    }

    static SWIGPendingException() {
      exceptionsLock = new global::System.Object();
    }
  }


  protected class SWIGStringHelper {

    public delegate string SWIGStringDelegate(string message);
    static SWIGStringDelegate stringDelegate = new SWIGStringDelegate(CreateString);

    [global::System.Runtime.InteropServices.DllImport("KYCDocumentsVerifSDK", EntryPoint="SWIGRegisterStringCallback_KYCDocumentsVerifSDK")]
    public static extern void SWIGRegisterStringCallback_KYCDocumentsVerifSDK(SWIGStringDelegate stringDelegate);

    static string CreateString(string cString) {
      return cString;
    }

    static SWIGStringHelper() {
      SWIGRegisterStringCallback_KYCDocumentsVerifSDK(stringDelegate);
    }
  }

  static protected SWIGStringHelper swigStringHelper = new SWIGStringHelper();


  public class SWIGStringWithLengthHelper {

    [global::System.Runtime.InteropServices.DllImport("KYCDocumentsVerifSDK", EntryPoint="SWIG_csharp_string_to_c")]
    private static extern global::System.IntPtr SWIG_csharp_string_to_c0(int size, int len, [global::System.Runtime.InteropServices.In,global::System.Runtime.InteropServices.MarshalAs(global::System.Runtime.InteropServices.UnmanagedType.LPStr, SizeParamIndex=0)] string str);

    [global::System.Runtime.InteropServices.DllImport("KYCDocumentsVerifSDK", EntryPoint="SWIG_csharp_string_size")]
    private static extern int SWIG_csharp_string_size(global::System.IntPtr str);

    [global::System.Runtime.InteropServices.DllImport("KYCDocumentsVerifSDK", EntryPoint="SWIG_csharp_string_str")]
    private static extern global::System.IntPtr SWIG_csharp_string_str(global::System.IntPtr str);

    public static global::System.IntPtr SWIG_csharp_string_to_c(string str) {
      if (str == null)
        return global::System.IntPtr.Zero;
      global::System.Text.Encoding utf8 = global::System.Text.Encoding.UTF8;
      return SWIG_csharp_string_to_c0(utf8.GetByteCount(str), str.Length, str);
    }

    public static string SWIG_c_to_csharp_string(global::System.IntPtr str) {
      int size = SWIG_csharp_string_size(str);
      if (size > 0) {
        global::System.IntPtr s = SWIG_csharp_string_str(str);
        byte[] b = new byte[size];
        global::System.Runtime.InteropServices.Marshal.Copy(s, b, 0, size);
        global::System.Text.Encoding utf8 = global::System.Text.Encoding.UTF8;
        return utf8.GetString(b);
      }
      return null;
    }
  }


  static KYCDocumentsVerifSDKPINVOKE() {
  }


  [global::System.Runtime.InteropServices.DllImport("KYCDocumentsVerifSDK", EntryPoint="CSharp_orgfdoubangofKycVeriffSdk_KYC_VERIF_SDK_VERSION_MAJOR_get___")]
  public static extern int KYC_VERIF_SDK_VERSION_MAJOR_get();

  [global::System.Runtime.InteropServices.DllImport("KYCDocumentsVerifSDK", EntryPoint="CSharp_orgfdoubangofKycVeriffSdk_KYC_VERIF_SDK_VERSION_MINOR_get___")]
  public static extern int KYC_VERIF_SDK_VERSION_MINOR_get();

  [global::System.Runtime.InteropServices.DllImport("KYCDocumentsVerifSDK", EntryPoint="CSharp_orgfdoubangofKycVeriffSdk_KYC_VERIF_SDK_VERSION_MICRO_get___")]
  public static extern int KYC_VERIF_SDK_VERSION_MICRO_get();

  [global::System.Runtime.InteropServices.DllImport("KYCDocumentsVerifSDK", EntryPoint="CSharp_orgfdoubangofKycVeriffSdk_new_KycVerifSdkResult__SWIG_0___")]
  public static extern global::System.IntPtr new_KycVerifSdkResult__SWIG_0();

  [global::System.Runtime.InteropServices.DllImport("KYCDocumentsVerifSDK", EntryPoint="CSharp_orgfdoubangofKycVeriffSdk_new_KycVerifSdkResult__SWIG_1___")]
  public static extern global::System.IntPtr new_KycVerifSdkResult__SWIG_1(int jarg1, string jarg2, string jarg3, uint jarg4);

  [global::System.Runtime.InteropServices.DllImport("KYCDocumentsVerifSDK", EntryPoint="CSharp_orgfdoubangofKycVeriffSdk_new_KycVerifSdkResult__SWIG_2___")]
  public static extern global::System.IntPtr new_KycVerifSdkResult__SWIG_2(int jarg1, string jarg2, string jarg3);

  [global::System.Runtime.InteropServices.DllImport("KYCDocumentsVerifSDK", EntryPoint="CSharp_orgfdoubangofKycVeriffSdk_new_KycVerifSdkResult__SWIG_3___")]
  public static extern global::System.IntPtr new_KycVerifSdkResult__SWIG_3(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("KYCDocumentsVerifSDK", EntryPoint="CSharp_orgfdoubangofKycVeriffSdk_delete_KycVerifSdkResult___")]
  public static extern void delete_KycVerifSdkResult(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("KYCDocumentsVerifSDK", EntryPoint="CSharp_orgfdoubangofKycVeriffSdk_KycVerifSdkResult_code___")]
  public static extern int KycVerifSdkResult_code(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("KYCDocumentsVerifSDK", EntryPoint="CSharp_orgfdoubangofKycVeriffSdk_KycVerifSdkResult_phrase___")]
  public static extern string KycVerifSdkResult_phrase(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("KYCDocumentsVerifSDK", EntryPoint="CSharp_orgfdoubangofKycVeriffSdk_KycVerifSdkResult_json___")]
  public static extern string KycVerifSdkResult_json(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("KYCDocumentsVerifSDK", EntryPoint="CSharp_orgfdoubangofKycVeriffSdk_KycVerifSdkResult_numVIZs___")]
  public static extern uint KycVerifSdkResult_numVIZs(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("KYCDocumentsVerifSDK", EntryPoint="CSharp_orgfdoubangofKycVeriffSdk_KycVerifSdkResult_isOK___")]
  public static extern bool KycVerifSdkResult_isOK(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("KYCDocumentsVerifSDK", EntryPoint="CSharp_orgfdoubangofKycVeriffSdk_delete_KycVerifSdkParallelDeliveryCallback___")]
  public static extern void delete_KycVerifSdkParallelDeliveryCallback(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("KYCDocumentsVerifSDK", EntryPoint="CSharp_orgfdoubangofKycVeriffSdk_KycVerifSdkParallelDeliveryCallback_onNewResult___")]
  public static extern void KycVerifSdkParallelDeliveryCallback_onNewResult(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("KYCDocumentsVerifSDK", EntryPoint="CSharp_orgfdoubangofKycVeriffSdk_KycVerifSdkEngine_init__SWIG_0___")]
  public static extern global::System.IntPtr KycVerifSdkEngine_init__SWIG_0(string jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("KYCDocumentsVerifSDK", EntryPoint="CSharp_orgfdoubangofKycVeriffSdk_KycVerifSdkEngine_init__SWIG_1___")]
  public static extern global::System.IntPtr KycVerifSdkEngine_init__SWIG_1(string jarg1);

  [global::System.Runtime.InteropServices.DllImport("KYCDocumentsVerifSDK", EntryPoint="CSharp_orgfdoubangofKycVeriffSdk_KycVerifSdkEngine_init__SWIG_2___")]
  public static extern global::System.IntPtr KycVerifSdkEngine_init__SWIG_2();

  [global::System.Runtime.InteropServices.DllImport("KYCDocumentsVerifSDK", EntryPoint="CSharp_orgfdoubangofKycVeriffSdk_KycVerifSdkEngine_deInit___")]
  public static extern global::System.IntPtr KycVerifSdkEngine_deInit();

  [global::System.Runtime.InteropServices.DllImport("KYCDocumentsVerifSDK", EntryPoint="CSharp_orgfdoubangofKycVeriffSdk_KycVerifSdkEngine_process__SWIG_0___")]
  public static extern global::System.IntPtr KycVerifSdkEngine_process__SWIG_0(int jarg1, IntPtr jarg2, uint jarg3, uint jarg4, uint jarg5, int jarg6);

  [global::System.Runtime.InteropServices.DllImport("KYCDocumentsVerifSDK", EntryPoint="CSharp_orgfdoubangofKycVeriffSdk_KycVerifSdkEngine_process__SWIG_1___")]
  public static extern global::System.IntPtr KycVerifSdkEngine_process__SWIG_1(int jarg1, IntPtr jarg2, uint jarg3, uint jarg4, uint jarg5);

  [global::System.Runtime.InteropServices.DllImport("KYCDocumentsVerifSDK", EntryPoint="CSharp_orgfdoubangofKycVeriffSdk_KycVerifSdkEngine_process__SWIG_2___")]
  public static extern global::System.IntPtr KycVerifSdkEngine_process__SWIG_2(int jarg1, IntPtr jarg2, uint jarg3, uint jarg4);

  [global::System.Runtime.InteropServices.DllImport("KYCDocumentsVerifSDK", EntryPoint="CSharp_orgfdoubangofKycVeriffSdk_KycVerifSdkEngine_process__SWIG_3___")]
  public static extern global::System.IntPtr KycVerifSdkEngine_process__SWIG_3(int jarg1, IntPtr jarg2, IntPtr jarg3, IntPtr jarg4, uint jarg5, uint jarg6, uint jarg7, uint jarg8, uint jarg9, uint jarg10, int jarg11);

  [global::System.Runtime.InteropServices.DllImport("KYCDocumentsVerifSDK", EntryPoint="CSharp_orgfdoubangofKycVeriffSdk_KycVerifSdkEngine_process__SWIG_4___")]
  public static extern global::System.IntPtr KycVerifSdkEngine_process__SWIG_4(int jarg1, IntPtr jarg2, IntPtr jarg3, IntPtr jarg4, uint jarg5, uint jarg6, uint jarg7, uint jarg8, uint jarg9, uint jarg10);

  [global::System.Runtime.InteropServices.DllImport("KYCDocumentsVerifSDK", EntryPoint="CSharp_orgfdoubangofKycVeriffSdk_KycVerifSdkEngine_process__SWIG_5___")]
  public static extern global::System.IntPtr KycVerifSdkEngine_process__SWIG_5(int jarg1, IntPtr jarg2, IntPtr jarg3, IntPtr jarg4, uint jarg5, uint jarg6, uint jarg7, uint jarg8, uint jarg9);

  [global::System.Runtime.InteropServices.DllImport("KYCDocumentsVerifSDK", EntryPoint="CSharp_orgfdoubangofKycVeriffSdk_KycVerifSdkEngine_process__SWIG_6___")]
  public static extern global::System.IntPtr KycVerifSdkEngine_process__SWIG_6(IntPtr jarg1, uint jarg2);

  [global::System.Runtime.InteropServices.DllImport("KYCDocumentsVerifSDK", EntryPoint="CSharp_orgfdoubangofKycVeriffSdk_KycVerifSdkEngine_exifOrientation___")]
  public static extern int KycVerifSdkEngine_exifOrientation(IntPtr jarg1, uint jarg2);

  [global::System.Runtime.InteropServices.DllImport("KYCDocumentsVerifSDK", EntryPoint="CSharp_orgfdoubangofKycVeriffSdk_KycVerifSdkEngine_requestRuntimeLicenseKey__SWIG_0___")]
  public static extern global::System.IntPtr KycVerifSdkEngine_requestRuntimeLicenseKey__SWIG_0(bool jarg1);

  [global::System.Runtime.InteropServices.DllImport("KYCDocumentsVerifSDK", EntryPoint="CSharp_orgfdoubangofKycVeriffSdk_KycVerifSdkEngine_requestRuntimeLicenseKey__SWIG_1___")]
  public static extern global::System.IntPtr KycVerifSdkEngine_requestRuntimeLicenseKey__SWIG_1();

  [global::System.Runtime.InteropServices.DllImport("KYCDocumentsVerifSDK", EntryPoint="CSharp_orgfdoubangofKycVeriffSdk_delete_KycVerifSdkEngine___")]
  public static extern void delete_KycVerifSdkEngine(global::System.Runtime.InteropServices.HandleRef jarg1);
}

}
