//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.4.0
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace org.doubango.KycVerif.Sdk {

public class KYCDocumentsVerifSDK {
  public static readonly int KYC_VERIF_SDK_VERSION_MAJOR = KYCDocumentsVerifSDKPINVOKE.KYC_VERIF_SDK_VERSION_MAJOR_get();
  public static readonly int KYC_VERIF_SDK_VERSION_MINOR = KYCDocumentsVerifSDKPINVOKE.KYC_VERIF_SDK_VERSION_MINOR_get();
  public static readonly int KYC_VERIF_SDK_VERSION_MICRO = KYCDocumentsVerifSDKPINVOKE.KYC_VERIF_SDK_VERSION_MICRO_get();
}

}
