//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.4.0
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace org.doubango.KycVerif.Sdk {

public class KycVerifSdkEngine : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal KycVerifSdkEngine(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(KycVerifSdkEngine obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  internal static global::System.Runtime.InteropServices.HandleRef swigRelease(KycVerifSdkEngine obj) {
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
      global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.Dispose();
      return ptr;
    } else {
      return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
    }
  }

  ~KycVerifSdkEngine() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          KYCDocumentsVerifSDKPINVOKE.delete_KycVerifSdkEngine(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public static KycVerifSdkResult init(string jsonConfig, KycVerifSdkParallelDeliveryCallback parallelDeliveryCallback) {
    KycVerifSdkResult ret = new KycVerifSdkResult(KYCDocumentsVerifSDKPINVOKE.KycVerifSdkEngine_init__SWIG_0(jsonConfig, KycVerifSdkParallelDeliveryCallback.getCPtr(parallelDeliveryCallback)), true);
    return ret;
  }

  public static KycVerifSdkResult init(string jsonConfig) {
    KycVerifSdkResult ret = new KycVerifSdkResult(KYCDocumentsVerifSDKPINVOKE.KycVerifSdkEngine_init__SWIG_1(jsonConfig), true);
    return ret;
  }

  public static KycVerifSdkResult init() {
    KycVerifSdkResult ret = new KycVerifSdkResult(KYCDocumentsVerifSDKPINVOKE.KycVerifSdkEngine_init__SWIG_2(), true);
    return ret;
  }

  public static KycVerifSdkResult deInit() {
    KycVerifSdkResult ret = new KycVerifSdkResult(KYCDocumentsVerifSDKPINVOKE.KycVerifSdkEngine_deInit(), true);
    return ret;
  }

  public static KycVerifSdkResult process(KYC_VERIF_SDK_IMAGE_TYPE imageType, IntPtr imageDataPtr, uint imageWidthInSamples, uint imageHeightInSamples, uint imageStrideInSamples, int imageExifOrientation) {
    KycVerifSdkResult ret = new KycVerifSdkResult(KYCDocumentsVerifSDKPINVOKE.KycVerifSdkEngine_process__SWIG_0((int)imageType, imageDataPtr, imageWidthInSamples, imageHeightInSamples, imageStrideInSamples, imageExifOrientation), true);
    return ret;
  }

  public static KycVerifSdkResult process(KYC_VERIF_SDK_IMAGE_TYPE imageType, IntPtr imageDataPtr, uint imageWidthInSamples, uint imageHeightInSamples, uint imageStrideInSamples) {
    KycVerifSdkResult ret = new KycVerifSdkResult(KYCDocumentsVerifSDKPINVOKE.KycVerifSdkEngine_process__SWIG_1((int)imageType, imageDataPtr, imageWidthInSamples, imageHeightInSamples, imageStrideInSamples), true);
    return ret;
  }

  public static KycVerifSdkResult process(KYC_VERIF_SDK_IMAGE_TYPE imageType, IntPtr imageDataPtr, uint imageWidthInSamples, uint imageHeightInSamples) {
    KycVerifSdkResult ret = new KycVerifSdkResult(KYCDocumentsVerifSDKPINVOKE.KycVerifSdkEngine_process__SWIG_2((int)imageType, imageDataPtr, imageWidthInSamples, imageHeightInSamples), true);
    return ret;
  }

  public static KycVerifSdkResult process(KYC_VERIF_SDK_IMAGE_TYPE imageType, IntPtr yPtr, IntPtr uPtr, IntPtr vPtr, uint widthInSamples, uint heightInSamples, uint yStrideInBytes, uint uStrideInBytes, uint vStrideInBytes, uint uvPixelStrideInBytes, int exifOrientation) {
    KycVerifSdkResult ret = new KycVerifSdkResult(KYCDocumentsVerifSDKPINVOKE.KycVerifSdkEngine_process__SWIG_3((int)imageType, yPtr, uPtr, vPtr, widthInSamples, heightInSamples, yStrideInBytes, uStrideInBytes, vStrideInBytes, uvPixelStrideInBytes, exifOrientation), true);
    return ret;
  }

  public static KycVerifSdkResult process(KYC_VERIF_SDK_IMAGE_TYPE imageType, IntPtr yPtr, IntPtr uPtr, IntPtr vPtr, uint widthInSamples, uint heightInSamples, uint yStrideInBytes, uint uStrideInBytes, uint vStrideInBytes, uint uvPixelStrideInBytes) {
    KycVerifSdkResult ret = new KycVerifSdkResult(KYCDocumentsVerifSDKPINVOKE.KycVerifSdkEngine_process__SWIG_4((int)imageType, yPtr, uPtr, vPtr, widthInSamples, heightInSamples, yStrideInBytes, uStrideInBytes, vStrideInBytes, uvPixelStrideInBytes), true);
    return ret;
  }

  public static KycVerifSdkResult process(KYC_VERIF_SDK_IMAGE_TYPE imageType, IntPtr yPtr, IntPtr uPtr, IntPtr vPtr, uint widthInSamples, uint heightInSamples, uint yStrideInBytes, uint uStrideInBytes, uint vStrideInBytes) {
    KycVerifSdkResult ret = new KycVerifSdkResult(KYCDocumentsVerifSDKPINVOKE.KycVerifSdkEngine_process__SWIG_5((int)imageType, yPtr, uPtr, vPtr, widthInSamples, heightInSamples, yStrideInBytes, uStrideInBytes, vStrideInBytes), true);
    return ret;
  }

  public static KycVerifSdkResult process(IntPtr encodedDataPtr, uint encodedDataSize) {
    KycVerifSdkResult ret = new KycVerifSdkResult(KYCDocumentsVerifSDKPINVOKE.KycVerifSdkEngine_process__SWIG_6(encodedDataPtr, encodedDataSize), true);
    return ret;
  }

  public static int exifOrientation(IntPtr jpegMetaDataPtr, uint jpegMetaDataSize) {
    int ret = KYCDocumentsVerifSDKPINVOKE.KycVerifSdkEngine_exifOrientation(jpegMetaDataPtr, jpegMetaDataSize);
    return ret;
  }

  public static KycVerifSdkResult requestRuntimeLicenseKey(bool rawInsteadOfJSON) {
    KycVerifSdkResult ret = new KycVerifSdkResult(KYCDocumentsVerifSDKPINVOKE.KycVerifSdkEngine_requestRuntimeLicenseKey__SWIG_0(rawInsteadOfJSON), true);
    return ret;
  }

  public static KycVerifSdkResult requestRuntimeLicenseKey() {
    KycVerifSdkResult ret = new KycVerifSdkResult(KYCDocumentsVerifSDKPINVOKE.KycVerifSdkEngine_requestRuntimeLicenseKey__SWIG_1(), true);
    return ret;
  }

}

}
