//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.4.0
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace org.doubango.KycVerif.Sdk {

public class KycVerifSdkResult : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal KycVerifSdkResult(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(KycVerifSdkResult obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  internal static global::System.Runtime.InteropServices.HandleRef swigRelease(KycVerifSdkResult obj) {
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
      global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.Dispose();
      return ptr;
    } else {
      return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
    }
  }

  ~KycVerifSdkResult() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          KYCDocumentsVerifSDKPINVOKE.delete_KycVerifSdkResult(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public KycVerifSdkResult() : this(KYCDocumentsVerifSDKPINVOKE.new_KycVerifSdkResult__SWIG_0(), true) {
  }

  public KycVerifSdkResult(int code, string phrase, string json, uint numFaces) : this(KYCDocumentsVerifSDKPINVOKE.new_KycVerifSdkResult__SWIG_1(code, phrase, json, numFaces), true) {
  }

  public KycVerifSdkResult(int code, string phrase, string json) : this(KYCDocumentsVerifSDKPINVOKE.new_KycVerifSdkResult__SWIG_2(code, phrase, json), true) {
  }

  public KycVerifSdkResult(KycVerifSdkResult other) : this(KYCDocumentsVerifSDKPINVOKE.new_KycVerifSdkResult__SWIG_3(KycVerifSdkResult.getCPtr(other)), true) {
    if (KYCDocumentsVerifSDKPINVOKE.SWIGPendingException.Pending) throw KYCDocumentsVerifSDKPINVOKE.SWIGPendingException.Retrieve();
  }

  public int code() {
    int ret = KYCDocumentsVerifSDKPINVOKE.KycVerifSdkResult_code(swigCPtr);
    return ret;
  }

  public string phrase() {
    string ret = KYCDocumentsVerifSDKPINVOKE.KycVerifSdkResult_phrase(swigCPtr);
    return ret;
  }

  public string json() {
    string ret = KYCDocumentsVerifSDKPINVOKE.KycVerifSdkResult_json(swigCPtr);
    return ret;
  }

  public uint numVIZs() {
    uint ret = KYCDocumentsVerifSDKPINVOKE.KycVerifSdkResult_numVIZs(swigCPtr);
    return ret;
  }

  public bool isOK() {
    bool ret = KYCDocumentsVerifSDKPINVOKE.KycVerifSdkResult_isOK(swigCPtr);
    return ret;
  }

}

}
