/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.4.0
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.doubango.KycVerif.Sdk;

public interface KYCDocumentsVerifSDKConstants {
  public final static int KYC_VERIF_SDK_VERSION_MAJOR = 0;
  public final static int KYC_VERIF_SDK_VERSION_MINOR = 0;
  public final static int KYC_VERIF_SDK_VERSION_MICRO = 14;
}
