/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.4.0
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.doubango.KycVerif.Sdk;

public class KycVerifSdkResult {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected KycVerifSdkResult(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(KycVerifSdkResult obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(KycVerifSdkResult obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        KYCDocumentsVerifSDKJNI.delete_KycVerifSdkResult(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public KycVerifSdkResult() {
    this(KYCDocumentsVerifSDKJNI.new_KycVerifSdkResult__SWIG_0(), true);
  }

  public KycVerifSdkResult(int code, String phrase, String json, long numFaces) {
    this(KYCDocumentsVerifSDKJNI.new_KycVerifSdkResult__SWIG_1(code, phrase, json, numFaces), true);
  }

  public KycVerifSdkResult(int code, String phrase, String json) {
    this(KYCDocumentsVerifSDKJNI.new_KycVerifSdkResult__SWIG_2(code, phrase, json), true);
  }

  public KycVerifSdkResult(KycVerifSdkResult other) {
    this(KYCDocumentsVerifSDKJNI.new_KycVerifSdkResult__SWIG_3(KycVerifSdkResult.getCPtr(other), other), true);
  }

  public int code() {
    return KYCDocumentsVerifSDKJNI.KycVerifSdkResult_code(swigCPtr, this);
  }

  public String phrase() {
    return KYCDocumentsVerifSDKJNI.KycVerifSdkResult_phrase(swigCPtr, this);
  }

  public String json() {
    return KYCDocumentsVerifSDKJNI.KycVerifSdkResult_json(swigCPtr, this);
  }

  public long numVIZs() {
    return KYCDocumentsVerifSDKJNI.KycVerifSdkResult_numVIZs(swigCPtr, this);
  }

  public boolean isOK() {
    return KYCDocumentsVerifSDKJNI.KycVerifSdkResult_isOK(swigCPtr, this);
  }

}
